bind r source-file ~/.tmux.conf
set-option -g set-titles on
set-option -g history-limit 20000
setw -g mode-keys vi
set -g base-index 1
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind '<' swap-window -t -1
bind '>' swap-window -t +1

bind -n S-Left resize-pane -L 2
bind -n S-Right resize-pane -R 2
bind -n S-Down resize-pane -D 1
bind -n S-Up resize-pane -U 1
bind -n S-Left resize-pane -L 10
bind -n S-Right resize-pane -R 10
bind -n S-Down resize-pane -D 5
bind -n S-Up resize-pane -U 5
bind-key b break-pane -d
set -g status-keys vi
set -g status-interval 1
set -g status-fg white
set -g status-bg default
set -g status-left-length 20
set -g status-left '#[fg=green][#[fg=red]#S#[fg=green]]#[default]'
set -g status-justify centre
set -g status-right '#[fg=green][ %m/%d %H:%M:%S ]#[default]'
setw -g window-status-current-format '#[fg=yellow](#I #F#W)#[default]'
setw -g window-status-format '#I #F#W'
setw -g monitor-activity on
set -g visual-activity on
set -g display-time 6000
#setw -g window-active-style 'bg=#330000'
#setw -g window-style 'bg=black'
bind-key - split-window -v -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'
set -g default-terminal 'tmux-256color'
#set -g window-style 'fg=colour247,bg=colour236'
#set -g window-active-style 'fg=colour250,bg=black'
set -g mouse on

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send-keys -X cancel
bind -n C-y run 'tmux save buffer - | /c/windows/System32/clip.exe' \; display-message 'Clipboard copied'
